default_platform(:ios)

platform :ios do
  desc "Build the iOS app for TestFlight / App Store"
  lane :build_and_export do
    # Build the app using gym
    gym(
      project: "App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      export_team_id: "4367ZCH572",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=4367ZCH572 PROVISIONING_PROFILE_SPECIFIER='Squito Pest Control App' CODE_SIGN_IDENTITY='Apple Distribution' CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES",
      clean: true,
      output_directory: "./build",
      output_name: "SquitoApp.ipa"
    )
  end
end
