default_platform(:ios)

platform :ios do
  desc "Build the iOS app for TestFlight / App Store"
  lane :build_and_export do
    # Build the app using gym
    gym(
      project: "App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      export_team_id: "4367ZCH572",
      xcargs: "DEVELOPMENT_TEAM=4367ZCH572",
      clean: true,
      output_directory: "./build",
      output_name: "SquitoApp.ipa"
    )
  end
end
